puppetlabs/puppetlabs-splunk_hec

LICENSE, metadata.json
Metadata update for 0.5.0 release.
Updates license file to include Puppet and year
=> Updates for 0.5.0 release

.github/workflows/ci.yml
The puppet class tests were not being automatically run by CI.
=> (PIE-320) Run unit tests via github actions

tasks/collect_api_events.rb
These were selected by Kevin to match the types of API data we are posting to splunk. 
A small fix was required to the hostname to get it to send to splunk.
=> (PIE-422) Add the new source types to the collection task

.fixtures.yml, Gemfile, scripts/collect_api_events.rb
Change the common events gem github ref from an ssh based reference to
an HTTP protocol reference. This should allow the github actions in the
repository to start working.
=> (MAINT) Fix Gemfile Common Events Ref

Gemfile, scripts/collect_api_events.rb
=> (PIE-426) Support for API offset and tombstoning ID's

README.md, manifests/collect_events.pp, manifests/init.pp, spec/classes/init_spec.rb
Added documentation to the readme.
Added an optional parameter to turn off the api collection.
=> (PIE-445) Added the collector class to the init.pp

conf/splunk_config.yaml, scripts/collect_api_events.rb
The two APIs return the total rows differently. It can be nil or zero :|
=> (PIE-451) Fix the URI handing if the total returned is nil not zero

scripts/collect_api_events.rb
This will line up with PIE-446.
=> (maint) Added the new source types to the collect script

conf/splunk_config.yaml, files/splunk_hec_collect_api_events.rb, manifests/init.pp, spec/classes/init_spec.rb, templates/splunk_hec.yaml.epp
Previously the API Collection script had its own configuration file.
This change moves a couple items of configuration into the main splunk
configuration file and changes the API collection script to work with that
file instead.
It also implements the Sensitive data type for the pe console password
parameter.
Co-authored-by: Greg Sparks <gregleesparks@gmail.com>
=> (PIE-456) Refactor API Collection Config

files/splunk_hec_collect_api_events.rb
Changed offset behavior to be consistent with Orchestrator api because
Orchestrator offsets count down from the newest record vs counting up
from the oldest.
=> (PIE-463) Fix orchestrator offset bug

files/splunk_hec_collect_api_events.rb
Similar to the Orchestrator jobs api we modify the Activity api to use
newest first pagination where offset counts down from the newest events.
=> (PIE-464) Fix Events API to work newest first pagination

README.md
Added instructions to set the new Splunk_hec activity events API
parameters as well as install the common events module.
=> (PIE-462) Update ReadME for API collection parameters

files/splunk_hec_collect_api_events.rb
Common events code has changed slightly, so the names of the methods
and properties that need to be called need to be fixed in here to
account for it.
There is also much less JSON parsing to do here in this file because it
is now handled in the library code.
=> (MAINT) Adjust code to work with Common Events

files/splunk_hec_collect_api_events.rb, manifests/init.pp
Switch to passing in the confdir and the modulepath instead of executing
Puppet with every run to get this data.
=> (MAINT) Pass in paths

.rubocop.yml, manifests/init.pp, spec/acceptance/class_spec.rb, spec/spec_helper_acceptance_local.rb, spec/support/acceptance/shared_context.rb, spec/support/acceptance/shared_examples.rb
This change adds an acceptance test for Token Authorization module for
PE. As part of this change the tests were made a little more flexible
and composable to make it easier to add future tests and to make this
new test work.
=> (PIE-478) Acceptance Test for Token Auth

.github/pull_request_template.md
Let me know in PR comments here if you would like to see anything changed or added to the template.
=> MAINT Add PR Template

spec/support/acceptance/helpers.rb
Call PuppetLitmus.configure! in the helper which complies with the
litmus docs.
[ ] Draft PR?
[ ] Tags
[ ] Unit Tests
=> (PIE-569) Configure Puppet Litmus Correctly

Jenkinsfile
Internal CI move to k8s 
[ ] Draft PR?
[x] Ensure README is updated
[x] Tags
[x] Unit Tests
[x] Acceptance Tests
[x] Commit title matches PR title
=> (DIO-1366) move to k8s

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .fixtures.yml, .gitignore, .gitlab-ci.yml, .pdkignore, .puppet-lint.rc, .rubocop.yml, .sync.yml, .vscode/extensions.json, Gemfile, Rakefile, appveyor.yml, lib/puppet/application/splunk_hec.rb, metadata.json, provision.yaml, spec/default_facts.yml, spec/spec_helper.rb, spec/spec_helper_acceptance_local.rb, spec/support/acceptance/helpers.rb
Ran pdk update and accepted new changes such as:
- Unpinned the litmus and provision module versions.
- Updated the .sync.yaml in order to keep our setup for local testing.
- Provision from abs instead of vms
[ ] Draft PR?
[ ] Tags
[ ] Unit Tests
=> PIE-686 Make splunk_hec PDK compliant

.fixtures.yml, .github/workflows/integration_test.yml, lib/puppet/reports/splunk_hec.rb, plans/provision_machines.pp, plans/server_setup.pp, rakelib/helpers.rake, spec/acceptance/class_spec.rb, spec/spec_helper_acceptance_local.rb, spec/support/acceptance/helpers.rb, spec/support/acceptance/splunk/docker-compose.yml, spec/support/acceptance/start_splunk_instance.sh
Implementing cloud ci acceptance testing
[ ] Draft PR?
[ ] Tags
[ ] Unit Tests
=> PIE-671 Implement Cloud CI

.github/workflows/release.yml
Added secrets syntax by adding the character '$'.
[ ] Draft PR?
[ ] Tags
[ ] Unit Tests
=> MAINT Fix release.yml syntax

provision.yaml, spec/spec_helper_acceptance_local.rb
Fix PE service name
Fix role name in provision.yaml
[ ] Draft PR?
[ ] Tags
[ ] Unit Tests
=> MAINT Fix PE Acceptance Tests

.github/pull_request_template.md
[ ] Draft PR?
[ ] Tags
[ ] Unit Tests
=> (MAINT) Add Playbook to PR template

README.md
Added links to Puppet documentation at various parts of the README to
provide explanation/guidance about Puppet features.
[ ] Draft PR?
[ ] Tags
[ ] Unit Tests
=> PIE-487 Update README.md

CHANGELOG.md
The last release went out without the correct entry in the changelog.
[ ] Draft PR?
[ ] Tags
[ ] Unit Tests
=> (MAINT) Fix Changelog

CHANGELOG.md, lib/puppet/util/splunk_hec.rb
Made changes to util file to address change made to app file to fix timestamps
[n/a] Ensure README is updated
[n/a] Any changes to existing documentation
[n/a] Anything new added
[n/a] Link to external Puppet documentation
[x] Review [Support Playbook](https://confluence.puppetlabs.com/display/SUP/Splunk+HEC+Module+Support+Playbook) for any needed updates
[ ] Tags
[x] Unit Tests
[x] Acceptance Tests
[x] Commit title matches PR title
=> (PIE-766) Fix puppet:metrics sourcetype

manifests/init.pp, spec/classes/init_spec.rb, templates/util_splunk_hec.erb
Created a template file that will become the util helper file for the
splunk_hec processor.
[ ] Draft PR?
[ ] Tags
[ ] Unit Tests
=> PIE-836 Added Util File for Processor File

.fixtures.yml, CHANGELOG.md, Gemfile, files/splunk_hec.rb, manifests/init.pp, rakelib/helpers.rake, spec/acceptance/class_spec.rb, spec/acceptance/events_processor_spec.rb, spec/classes/init_spec.rb, spec/spec_helper_acceptance_local.rb, spec/support/acceptance/example_events_data.json, templates/util_splunk_hec.erb
Implement a processor to accept files produced by the
pe-events-forwarding feature.
[ ] Draft PR?
[ ] Tags
[ ] Unit Tests
=> (PIE-846) Implement Events Processor

README.md
[ ] Draft PR?
[ ] Tags
[ ] Unit Tests
=> (PIE-862) Update Readme for PE Event Forwarding

.github/workflows/release.yml
[ ] Draft PR?
[ ] Tags
[ ] Unit Tests
=> (MAINT) Fix Forge Deploy Workflow

.gitignore, .pdkignore, .sync.yml, Gemfile, appveyor.yml, manifests/init.pp, metadata.json, plans/acceptance/provision_machines.pp, spec/spec_helper.rb
Make module pdk compliant.
[ ] Draft PR?
[ ] Tags
[ ] Unit Tests
=> PIE-874 PDK Compliance

CHANGELOG.md, metadata.json
[ ] Draft PR?
[ ] Tags
[ ] Unit Tests
=> (Release Prep) Prep v1.0.1

README.md
This module depends on the puppetlabs-pe_event_forwarding module to
provide data for this modules own event forwarding feature. That module
needs a feature in the PE API that was added starting at Puppet 6.23.0,
but was not added to 7 series puppet until 7.8.0.
This means there is a gap in the version numbers that have this feature
that currently includes 7.4.1 and 7.6.1.
The forge does not have a supported method to represent a disjoint set
of version ranges like this. Our only choice is to specify a version
range that includes both of those versions, and then specify in the
README as clearly as possible, that there is a set of version numbers
within that range that we cannot support.
Specifically the feature is support for sorting activities by oldest to
newest in the events end point. …
=> (PIE-905) Add supported versions to README

README.md
Updated links in Customized Reporting section of the README.
=> (MAINT) Update Customized Reporting Links

REFERENCE.md, manifests/init.pp, plans/acceptance/pe_server_setup.pp, plans/acceptance/server_setup.pp
Please enter the commit message for your changes. Lines starting
[ ] Draft PR?
[ ] Tags
[ ] Unit Tests
=> (MAINT) Update Puppet Strings for events_reporting_enabled

spec/acceptance/class_spec.rb, spec/acceptance/events_processor_spec.rb
Reviewed the params in this module to add test stubs to `class_spec.rb`.
Wasn't too sure on the following params, so they have yet to be added:
* $pe_console
* $timeout
* $token_summary
* $token_facts
* $token_metrics
* $url_summary
* $url_facts
* $url_metrics
* $orchestrator_data_filter
* $rbac_data_filter
* $classifier_data_filter
* $pe_console_data_filter
* $code_manager_data_filter
=> (PIE-886) Add test stubs for scenarios not tested

metadata.json
Updated `metadata.json` for release v1.2.0.
[ ] Tags
[ ] Unit Tests
=> (PIE-1044) Release prep v1.2.0

README.md, metadata.json
flag.
[ ] Draft PR?
[ ] Tags
[ ] Unit Tests
=> (PIE-1049) Update README to reflect pe_event_forwarding disable_rbac

templates/util_splunk_hec.erb
Fixed the missing @ symbol in the util_splunk_hec.erb
[ ] Draft PR?
[ ] Tags
[ ] Unit Tests
=> MAINT Fix missing @ in confdir

.github/workflows/integration_test.yml
Added latest supported PE version to testing matrix.
[ ] Draft PR?
[ ] Tags
[ ] Unit Tests
=> PIE-1065 Add latest supported PE to testing

CHANGELOG.md, metadata.json
[ ] Draft PR?
[ ] Tags
[ ] Unit Tests
=> Release Prep v1.3.0

Gemfile, spec/unit/reports/splunk_hec_spec.rb
Add unit test for conditional `only_changes` parameter.
Changes to `spec/unit/reports/splunk_hec_spec.rb` to add testing against the optional `only_changes` parameter.
[X] Unit Tests
=> (PIE-1103) Add unit test for only_changes

spec/support/acceptance/start_splunk_instance.sh
This commit refactors `start_splunk_instance.sh` for CI testing to support Ubuntu.
The script now pulls the latest version of `docker` and `docker compose` with either `yum` or `apt`.
=> (PIE-1274) Refactor start_splunk_instance

CHANGELOG.md, metadata.json
Release prep for v1.4.0
Version bump / updates to `metadata.json` and `CHANGELOG.md`
=> (PIE-1299) Release Prep v1.4.0

lib/puppet/functions/splunk_hec/secure.rb, spec/spec_helper_acceptance_local.rb
This PR adds the custom function `splunk_hec::secure`.
* Adds `lib/puppet/functions/splunk_hec/secure.rb` to prepare for securing sensitive data utilized by this module.
=> (PIE-1340) Add custom function to secure data

spec/acceptance/class_spec.rb
This commit add rspec tests against SSL configuration.
* Add ssl verification tests to `spec/acceptance/class_spec.rb`.
=> (PIE-1395) SSL RSpec Testing

CHANGELOG.md
Release prep for v2.
* Marked `CHANGELOG.md` with new version.
=> (PIE-1376) release_prep

CHANGELOG.md, metadata.json
Release prep for **v2.0.1**
* Updated `metadata.json`
* Updated `CHANGELOG.md`
=> (PIE-1612) Release Prep
