puppetlabs/puppetlabs-splunk_hec

- metadata.json
RENAMES project links to puppetlabs-splunk_hec to conform with
internal naming guides for repos
> Fixes the issues and project links in the project

- lib/puppet/application/splunk_hec.rb
- lib/puppet/reports/splunk_hec.rb
- lib/puppet/util/splunk_hec.rb
- manifests/init.pp
- templates/splunk_hec.yaml.epp
This enables the splunk_hec plugin's report processor to save reports to disk along with adding the faces ability to upload them to splunk.
Essentially this lets us replay a HEC report submission whenever we want, for both testing the splunk demos and validating we are creating the properly formatted events to send to splunk.
> (PIE-66) Adds store support

- README.md
- lib/puppet/indirector/facts/splunk_hec.rb
- lib/puppet/reports/splunk_hec.rb
- lib/puppet/util/splunk_hec.rb
- manifests/init.pp
- templates/splunk_hec.yaml.epp
In order for data to be submitted to different indexes in Splunk, we need to be sending it to different HEC's. This updates the splunk_hec.rb util functions to check to see if there is a user provided hec token matching the puppet sourcetype that the event specifies and uses that.
If there is no custom HEC present, it falls back to using the global HEC token.
> PIE-67 Support multiple indexes

- README.md
- lib/puppet/indirector/facts/splunk_hec.rb
- manifests/init.pp
- metadata.json
- templates/splunk_hec_routes.yaml.epp
Moves the splunk_hec fact terminus from being the primary terminus to the cache terminus. This allows for any code that checks to see if puppetdb is set as the primary terminus to work without modification (ie, catalog compilation in 2019.1, CD4PE impact analysis).
See Breaking Changes in ReadMe on steps you must take to adopt this change if you've enabled Fact support previously. In order to facility this change, we had to remove support for PuppetDB forwarding from splunk_hec and move it to yaml forwarding, as that is the role of the cache setting traditionally (to store facts as a yaml cache locally on the puppetserver).
> (PIE-82) Enable support for CD4PE

- lib/puppet/application/splunk_hec.rb
To ensure compatibility with PIE-51 this adds the debug flag and removes
redundant log message which was causing a failure.
> Fixes metrics uploading on splunk_hec application

- lib/puppet/application/splunk_hec.rb
Before this we assumed we would receive parsable json on standard in from the metrics executable regardless of number of systems involved.
Instead it would output a json hash for each server and not attempt to combine them into a valid array. This converts any hash received on STDIN into an array of hashes (even if its just an array of 1).
> PIE-178 Multiple Metrics in stdin

- lib/puppet/application/splunk_hec.rb
This commit updates the splunk_hec command to accept line-delimited JSON
metrics generated by recent versions of the puppet_metrics_collector
module.
See puppetlabs/puppetlabs-puppet_metrics_collector#44
> (PIE-178) Parse line-delimited JSON metrics

- CHANGELOG.md
- README.md
- metadata.json
Updated version number to 0.8.0 and updated the puppet_metrics_collector
to require version 6.0.0.
> (Maint) update changelog for 0.8.0

- README.md
This change makes the recent docs refactor compatible with the forge as
relative linking is not supported on the forge.
> Replace relative docs links with static links

- .fixtures.yml
- docs/custom_installation.md
- manifests/init.pp
- spec/classes/init_spec.rb
- spec/spec_helper.rb
This option is enabled when $reports == '' for backwards compatibility.
The option's useful because it no longer requires the user to specify
_all_ of their report processors in the $reports param. This leads to a
better UX especially when the user wants to use another report processor
module because they do not have to update the $reports parameter to
include that module's report processor.
Note that the $reports parameter will eventually be deprecated.
Signed-off-by: Enis Inan <enis.inan@puppet.com>
> (PIE-296) Add option to dynamically calculate the 'reports' setting

- manifests/init.pp
- spec/classes/init_spec.rb
This still works, and also fixes a (strange) bug where the 'store'
report processor was being included in the list of report processors
when used with a live PE environment.
Signed-off-by: Enis Inan <enis.inan@puppet.com>
> (PIE-296) Use pe_ini_subsetting to automatically add report processor

- README.md
Relative image URLs in module READMEs don't render on the Forge. See https://tickets.puppetlabs.com/browse/FORGE-479.
Replace the relative image URLs with absolute ones pointing to GitHub.
> (docs) Work around FORGE-479

- .github/workflows/release.yml
- .github/workflows/release_prep.yml
- CONTRIBUTING.md
Add the release_prep step from the reporting integration which creates
the release PR and updates the release action to be consistent. At some
point we may want to update the name of the password secret from token
to password in github since it actually refers to the puppetlabs account
password. Tokens are not supported with the Puppetlabs user.
> (PIE-328) Standardize Release Actions

- spec/acceptance/class_spec.rb
A test in the acceptance suite expects
/opt/puppetlabs/puppet/cache/reports/ on the puppet server to contain a
report file with a .json extension. This test is now failing because the
report file has a .yaml extension. We don't currently understand what
caused this change, but the reports are being generated without issue
which was the intent of the test. It's not clear that a change to this
module was responsible. This change modifies the expectation of the test
from a .json to a .yaml file.
> (MAINT) Expect report files on puppet server to have a .yaml extension.

- provision.yaml
- spec/support/acceptance/install_pe.sh
This change updates the PE install script to test on the latest LTS
version of PE and makes it work more reliably for future versions or
other previous versions if the script is ever parameterized for matrix
testing builds.
> (MAINT) Update PE install script

- metadata.json
The team will not be using Github issues to track work as it is
difficult to prioritize. This change updates the issues URL on the forge
to point at the PIE project in Jira so that any tickets created can be
triaged.
> (MAINT) Update project issues url

- .github/workflows/ci.yml
The fix for the github actions environment variable bug has been merged
into the upstream repository. This change reverts the workflow from
using a personal repo, back to the Puppetlabs repo.
> (MAINT) Revert Github Actions Change

- .github/workflows/release_prep.yml
Github change the way that environment variables must be set from one
step to another. Using the old method results in a workflow error. This
change updates the release-prep workflow to comply with the new method.
https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files
> (MAINT) Fix Environment Variables

- manifests/init.pp
- metadata.json
- plans/apply_example.pp
This PR does not update the pdk compatibility version to latest because pdk wants to manage files that have not been properly prepped for pdk management. We would need to create a separate ticket for that work.
> Fix PDK Validate Errors

- .github/workflows/ci.yml
The puppetlabs/action-litmus_spec action installs the `bundler` gem
using the `--user-install` flag to the `gem install` command. Doing this
installs the `bundler` gem to a user folder that is not on the PATH.
For some reason this has starting causing CI to fail.
This change switches to a user fork of the action until a fix can be
implemented in the upstream repository.
> (MAINT) Fix gem user install bug

- .github/workflows/ci.yml
The fix for the underlying issue has been merged into the upstream
actions repo. This change can now be reverted.
> (MAINT) Revert CI fix

- lib/puppet/reports/splunk_hec.rb
Prior to this change, Puppet 4 installs would fail due to lack of
`job_id` or `code_id` in the report format.
This change detects the report format version and adds those variables
as needed to prevent errors.
> (MAINT) Fix Puppet 4 Compatibility

- lib/facter/splunk_hec_is_pe.rb
- lib/puppet/application/splunk_hec.rb
- lib/puppet/indirector/facts/splunk_hec.rb
- lib/puppet/reports/splunk_hec.rb
- manifests/init.pp
- spec/classes/init_spec.rb
Prior to this change the values for the of the resource parameters were
hard coded to match Puppet Enterprise.
This change enables the module to determine if it is in a PE environment
or Open Source, and select the appropriate values to avoid errors.
It also fixes a bug in the `requires` statements to account for path
differences between PE and Open Source.
> (PIE-431) Fix Open Source Compatibility

- README.md
- lib/facter/splunk_hec_is_pe.rb
- lib/puppet/application/splunk_hec.rb
- lib/puppet/indirector/facts/splunk_hec.rb
- lib/puppet/reports/splunk_hec.rb
- manifests/init.pp
- spec/classes/init_spec.rb
- templates/splunk_hec.yaml.epp
These being a hash is default Puppet behaviour, but this can make writing splunk queries very hard. Arrays are probably preferable but we likely don't want to change the default behaviour without a major release
> Added the ability to change resources format

- .githooks/pre-commit
This change adds a pre-commit hook that runs synax and linting checks,
then runs spec prep, and runs spec tests, before allowing a commit.
Acceptance tests are not run.
To ensure your local git installation runs any hooks we put in the
.githooks folder you need to run the following command on your local
machine. `git config core.hooksPath .githooks`
> (MAINT) Add pre-commit hook

- manifests/init.pp
- spec/classes/init_spec.rb
> (PIE-455) Show the deprecation warning only when the report parameter

- spec/support/acceptance/splunk/docker-compose.yml
The Splunk container requires Splunkbase credentials to pull the Report
Viewer App from Splunkbase and install it into the container for
testing. This change adds credentials that are only used for this and
can be easily recreated. Any Splunkbase account will do. Password has
been changed on the other account that was here previously which got
some editing permission after the creds were committed here.
> (MAINT) - Create a testing account to pull apps from Splunkbase

- files/splunk_hec_collect_api_events.rb
When the splunk_hec_collect_api_events.rb script is executed, the
`$LOAD_PATH` variable is not set to allow `require` to find the
`common_events_library` gem even though the module has been installed
into Puppet.
This change asks Puppet where the modules are installed, and finds the
correct module and adds the correct directory to `$LOAD_PATH` so that
requires statement will work.
> (PIE-459) Fix Ruby Loadpath for collector script

- files/splunk_hec_collect_api_events.rb
- spec/support/acceptance/splunk/docker-compose.yml
When running from `cron` we found that the PATH variable does not have
the expected directories added. This caused shell invocation of `puppet`
to fail because the program could not be found.
This change adds a normal set of directories back to PATH.
This change also points `docker-compose.yaml` at the internal
artifactory instance to avoid Docker Hub rate limits.
> (MAINT) Fix PATH Variable and Docker Rate Limit

- Jenkinsfile
- spec/acceptance/class_spec.rb
The Ruby version needs to be updated to solve a dependency problem in
CI.
> (MAINT) Fix Ruby Errors in Jenkins CI

- files/splunk_hec_collect_api_events.rb
Also added support for multiple services.
$ STORE_DIR=. bundle exec ruby files/splunk_hec_collect_api_events.rb
Sending 6 Orchestrator job(s) to Splunk.
Sending 21 classifier events(s) to Splunk.
Activity events for classifier sent to splunk
Sending 131 rbac events(s) to Splunk.
Activity events for rbac sent to splunk
Sending 6 pe-console events(s) to Splunk.
Activity events for pe-console sent to splunk
Sending 0 code-manager events(s) to Splunk.
$ STORE_DIR=. bundle exec ruby files/splunk_hec_collect_api_events.rb
Sending 0 Orchestrator job(s) to Splunk.
Sending 0 classifier events(s) to Splunk.
Sending 4 rbac events(s) to Splunk.
Activity events for rbac sent to splunk
Sending 0 pe-console events(s) to Splunk.
Sending 0 code-manager events(s) to Splunk.
> (PIE-468) Add events types to api collection

- manifests/init.pp
- spec/classes/init_spec.rb
When installing the module users who do not wish to use api collection
will be greeted with a validation error if the include_api_collection
parameter is set to true, but the pe_console, pe_username, and
pe_password parameters are not set. This changes the default to be false
so that exising users who are not using the api collection features will
not run into this validation.
> (MAINT) Default include_api_collection parameter to false

- files/splunk_hec_collect_api_events.rb
The hash table returned from the orchstrator API is different from that
returned by the Activity Service API. This change fixes the script to
look for the total number of jobs available in the correct place.
> (MAINT) Fix Orchestrator Events Not Sent Bug

- README.md
- manifests/init.pp
This sets the pe_console parameter to default to the fqdn of the
Puppet server it's installed on.
Co-authored-by: Sharon Nam <sharon.name@puppet.com>
> (PIE-471) Provide default value for console url

- files/splunk_hec_collect_api_events.rb
- spec/unit/splunk_hec_collect_api_events_spec.rb
Added function that removes the protocol from the pe_console.
This is to prevent the protocol from showing up in the host label in Splunk.
This does not affect the calls to the Orchestrator and Activity APIs.
Rearranged the script to be inside a main function so it's only run when called from cron 
so we can unit test it.
> (PIE-472) Strip protocol from host

- README.md
- files/splunk_hec_collect_api_events.rb
- manifests/init.pp
- templates/splunk_hec.yaml.epp
In order to prevent a pe username and password from being written to the
splunk_heck.yaml config file, the user may pass in a long lived pe
token instead. If a username and password as well as a token is
provided, the token will be used.
> (PIE-475) Orchestrator and Events classes accept a pe token.

- README.md
- files/splunk_hec_collect_api_events.rb
- spec/acceptance/class_spec.rb
This change makes the sourcet type names clearer and more specific.
For instance there are now four possible source types for events
coming from the Activity Service API. The events data itself for each
event did not contain a property that specific what kind of event it
was. The new source type names give users a top level peice of data
they can use to target specific kinds of events.
> (MAINT) Change source type names for clarity

- README.md
- Rakefile
- docs/custom_installation.md
- docs/troubleshooting_and_verification.md
- examples/splunk_hec.yaml
- files/splunk_hec_collect_api_events.rb
- lib/puppet/util/splunk_hec.rb
- manifests/init.pp
- spec/acceptance/class_spec.rb
- spec/classes/init_spec.rb
- spec/spec_helper_acceptance_local.rb
- spec/support/acceptance/site.pp
- spec/support/acceptance/splunk/default.yml
- spec/support/acceptance/splunk_hec.yaml
- templates/splunk_hec.yaml.epp
Changed $token to $splunk token for clarity because there is also
a $pe_token parameter.
> (PIE-477) Changed $token to $splunk_token

- Rakefile
Invoke `spec_prep` before `litmus:install_modules_from_directory`.
This will ensure that all of the modules this one depends on are
downloaded into `spec/fixtures/modules` in time to have them packaged
up by the Litmus rake task and installed onto the Puppet server.
> (MAINT) Update install_module Rake Task

- .rubocop.yml
- spec/acceptance/class_spec.rb
- spec/spec_helper_acceptance_local.rb
- spec/support/acceptance/shared_context.rb
- spec/support/acceptance/shared_examples.rb
Instead of using a time based splunk query to see how many events the
script sent to splunk, we switch to a `last n` events filter and just
test to see if we got the events we expected to get.
Switch from executing `master.run_cmd` five times, call it a single time
and execute a command that does the looping on the remote side.
Remove the need for instance variables and `before(:all)` blocks that
Rubocop doesn't like.
> (MAINT) Improve acceptance tests

- spec/support/acceptance/splunk/docker-compose-local.yml
- spec/support/acceptance/splunk/docker-compose.yml
This updates the splunk default.yaml file that configures the Splunk
container to pull the Report Viewer from Github as a tarball rather than
from Splunkbase.
> (PIE-458) Update Splunk container to pull Report Viewer from Github

- README.md
Updates to `README.md` to address PIE-551 and potentially PIE-351.
Moved **Custom Installation** section to `README.md`. Added a paragraph to point to the Puppet Alert Actions app and repo. Additional updates made to address markdown syntax, remove harmful terminology, PE console updates, and grammatical errors.
[ ] Draft PR?
[x] Ensure README is updated
[x] Any changes to existing documentation
[x] Anything new added
[x] Link to external Puppet documentation
[ ] Tags
[ ] Unit Tests
> (PIE-551) Docs Update

- .fixtures.yml
- Gemfile
- Rakefile
- spec/acceptance/class_spec.rb
This workaround pins the versions of the provision module and
puppet_litmus gem to work with the reporting_integration. Specifically
it restores functionality to provision with vmpooler and copy the
inventory file.
Provision module is set to a specific SHA.
Puppet_litmus is set to version 0.26.0 or earlier (lowerbound of 0.18).
[ ] Draft PR?
[ ] Tags
[ ] Unit Tests
> (PIE-606) Pin Litmus and Provision versions

- .gitignore
- .sync.yml
Add a sync yaml entry to ensure the litmus inventory file is ignored
by git to prevent it from being accidentally committed.
[ ] Draft PR?
[ ] Tags
[ ] Unit Tests
> MAINT Update .gitignore

- CHANGELOG.md
- lib/puppet/reports/splunk_hec.rb
- lib/puppet/util/splunk_hec.rb
- spec/support/unit/reports/splunk_hec_spec_helpers.rb
- spec/unit/reports/splunk_hec_spec.rb
Prior to this commit, the time stamp sent to Splunk as the `time`
property was only the time an agent run started.
This change adds the run duration to that property so that the time
stamp matches the time stamp found in the Console.
[ ] Draft PR?
[ ] Tags
[ ] Unit Tests
> (PIE-286) Fix Time Stamp

- CHANGELOG.md
- README.md
- REFERENCE.md
- lib/puppet/util/splunk_hec.rb
- manifests/init.pp
- spec/support/acceptance/splunk/default.yml
- templates/splunk_hec.yaml.epp
This change allows a user to provide a ca certificate file that
overrides the system trusted certificate store entirely.
Prior to this change, a ca certificate file provided to the `ssl_ca`
parameter was only a supplement to the system certificates store. This
could cause an issue where the system certificate store contained
invalid certificates and would cause certificate validation of the
splunk_hec end point to fail before the provided `ssl_ca` file was
checked.
This change fixes that bug by ensuring that only the provided file is
used for verification.
[ ] Draft PR?
[ ] Review [Support Playbook](https://confluence.puppetlabs.com/display/SUP/Splunk+HEC+ …
> (PIE-818) Allow Ignore System Certificate Store

- .fixtures.yml
- .github/workflows/integration_test.yml
- plans/acceptance/oss_server_setup.pp
- plans/acceptance/pe_server_setup.pp
- plans/acceptance/provision_machines.pp
- plans/acceptance/server_setup.pp
This change adds PE versions to the integration test matrix which was
previously Open Source only.
This is required because we now need to test PE Event forwarding as
well.
[ ] Draft PR?
[ ] Tags
[ ] Unit Tests
> (PIE-859) Add PE to test matrix

- rakelib/helpers.rake
- spec/spec_helper_acceptance_local.rb
These two functions had bugs that made executing the acceptance tests
from your local workstation more difficult.
[ ] Draft PR?
[ ] Tags
[ ] Unit Tests
> (MAINT) Fix local testing functions

- files/splunk_hec.rb
- spec/acceptance/events_processor_spec.rb
- templates/util_splunk_hec.erb
Modified util_splunk_hec and splunk_hec in the processors directory for
consistency. Now the processor only calls a function `extract_events`
for all indices (orchestrator and activity APIs).
[ ] Draft PR?
[ ] Tags
[ ] Unit Tests
> (MAINT) Change util splunk_hec

- .sync.yml
- Gemfile
Including the PDK gem in the Gemfile includes JSON pure improperly to
a version that is not compatible with Ruby 2.7
[ ] Draft PR?
[ ] Tags
[ ] Unit Tests
> (MAINT) Fix deprecation warnings

- CHANGELOG.md
- README.md
- REFERENCE.md
- files/splunk_hec.rb
- manifests/init.pp
- templates/splunk_hec.yaml.epp
Changes to ensure a user can select the type of events they would like to send.
Added param event_types to init.pp
Added event_types to splunk_hec.yaml template
Change to splunk_hec.rb file to iterate over event types
[X] Tags
[X] Unit Tests
> (PIE-863) Event Type Filtering

- CHANGELOG.md
- README.md
- REFERENCE.md
- files/splunk_hec.rb
- manifests/init.pp
- spec/acceptance/events_processor_spec.rb
- spec/spec_helper_acceptance_local.rb
- templates/splunk_hec.yaml.epp
- templates/util_splunk_hec.erb
Added query parameters for selecting which sub set of data they would
like to get in Splunk.
Allows users to send selective data; only the selected paths in each
category will be sent to Splunk. (Defaulted to sending all data to
Splunk)
[ ] Draft PR?
[ ] Tags
[ ] Unit Tests
> PIE-889 Add query parameter

- lib/puppet/application/splunk_hec.rb
The host field in Splunk for metrics data provides a formatted hostname replacing dots with dashes. In an attempt to utilize the pe_console field from facts data against the host field in the metrics data I discovered the mismatch between the host fields.
Adding the pe_console field to metric events allowed me to properly sort the hosts by the pe_console they are connected to.
> (SUP-2728) Add pe_console field to metric events

- lib/facter/splunk_hec_agent_only_node.rb
- manifests/init.pp
- spec/classes/init_spec.rb
The previous method in use for detecting when a node is an agent only
node had a bug. The fact being used to figure out the name of the server
node was not always present.
This method is more reliable and it's easier to unit test.
[ ] Draft PR?
[ ] Tags
[ ] Unit Tests
> (PIE-941) Detect running on non master node

- .github/workflows/release_prep.yml
We didn't realize when we removed the PDK gem from the Gemfile that this
workflow was the reason it was reason it was needed.
This change switches to using the PDK container so it doesn't have to be
installed.
[ ] Draft PR?
[ ] Tags
[ ] Unit Tests
> (MAINT) Fix Release Prep

- .github/workflows/ci.yml
- .github/workflows/release_prep.yml
Using Ruby 2.5.x caused bundle install errors during release prep.
Since 2.5.x is no longer supported by Puppet there's not reason to keep
using it.
[ ] Draft PR?
[ ] Tags
[ ] Unit Tests
> (MAINT) Update ruby versions for github actions.

- CHANGELOG.md
- README.md
- REFERENCE.md
- lib/puppet/indirector/facts/splunk_hec.rb
- manifests/init.pp
- templates/splunk_hec.yaml.epp
This PR adds the ability to collect all facts (including custom facts) by adding the special value `all.facts` to the `collect_facts` parameter. With the aforementioned special value configured, the optional `facts_blacklist` will be taken into consideration when collecting facts.
* Updated `lib/puppet/indirector/facts/splunk_hec.rb` to collect all facts when `all.facts` is in the `collect_facts` array.
* Added optional parameter `facts_blocklist`.
* Updated `README.md`.
* Updated `REFERENCE.md`.
* Updated `CHANGELOG.md`.
[X] Review [Support Playbook](https://confluence.puppetlabs.com/display/SUP/Splunk+HEC+Module+Support+Playbook) for any needed updates …
> (PIE-792) Send all facts to Splunk

- README.md
- docs/advanced_puppet_configuration.md
- docs/advanced_splunk_configuration.md
- docs/custom_installation.md
- docs/customized_reporting.md
- docs/fact_terminus_support.md
- docs/puppet_metrics_collector_support.md
- docs/ssl_support.md
- docs/troubleshooting_and_verification.md
Fixed a number of typos and syntax issues in the docs and README.
Over time sections of the docs have made it to the main README, then those new sections in the README are eventually updated. But the changes never make it back to the docs dir we link, so I've made changes to correct that. Additionally, I updated a number of links in the README so they will redirect to the latest version of Puppet docs.
[X] Review [Support Playbook](https://confluence.puppetlabs.com/display/SUP/Splunk+HEC+Module+Support+Playbook) for any needed updates
> (MAINT) Fix typos/syntax issues in docs and README

- CHANGELOG.md
- templates/splunk_hec.yaml.epp
Prevent `splunk_hec::event_type_filtering` from being added to `splunk_hec.yaml` unless event reporting is enabled.
Moved the `splunk_hec::event_type_filtering` parameter into the conditional for `splunk_hec::events_reporting_enabled` as the former is not required unless the latter is configured.
[X] Unit Tests
> (MAINT) Conditional event type filtering setting

- CHANGELOG.md
- README.md
- manifests/init.pp
- spec/classes/init_spec.rb
Prior to this commit, the suggestion of setting the `splunk_hec::reports` parameter to an empty string results in corrective changes as it removes **puppetdb** from the reports setting.
The new logic in `init.pp` prevents the `reports` parameter from configuring anything before throwing an updated warning message suggesting to set the parameter to `undef` or remove it entirely. It then will continue with adding `splunk_hec` to `puppet.conf` via the `ini_subsetting` resource.
> (PIE-1039) Update deprecated reports parameter

- files/splunk_hec.rb
pe_event_forwarding will soon have the ability to disable rbac event
collection for performance reasons. The is denoted in the index file
with a -1 value. We need to cover the case where rbac events are
enabled in splunk_hec but disabled in pe_event_forwarding. This check
will skip indicies with negative values.
[ ] Draft PR?
[ ] Tags
[ ] Unit Tests
> PIE-1047 Account for negative indicies

- manifests/init.pp
- spec/classes/init_spec.rb
The init.pp now accounts for customized confdirs from the
pe_event_forwarding module and places the proc files within the correct
directories.
[ ] Draft PR?
[ ] Tags
[ ] Unit Tests
> PIE-1032 Account for configured confdirs

- README.md
- lib/puppet/reports/splunk_hec.rb
- manifests/init.pp
- templates/splunk_hec.yaml.epp
A commonly requested feature for this module is the ability to send only reports that contain changes. This commit adds the ability to configure this type of functionality.
* Adding the new boolean parameter `splunk_hec::only_changes` to `init.pp`.
* When configured adding the setting to `splunk_hec.yaml`.
* Adding logic to `lib/puppet/reports/splunk_hec.rb` preventing report processing when the report status has not changed. 
* Updated **Customized Reporting** section in the `README`.
[ ] Unit Tests
[X] PR title is …
> (PIE-1102) Send only changed reports

- CHANGELOG.md
- lib/puppet/indirector/facts/splunk_hec.rb
Prior to this commit, if a user added any of the hardcoded facts to the block list a number of dashboards in Splunk would fail to populate.
* Updates to `lib/puppet/indirector/facts/splunk_hec.rb` to check the block list against the hardcoded list and rescue any matching facts.
[ ] Unit Tests
> (PIE-1059) Rescue hardcoded facts

- spec/unit/reports/splunk_hec_spec.rb
Moved `only_changes` to their own section and reversed the logic.
[X] Unit Tests
> (MAINT) Fix only_changes unit tests

- .github/workflows/ci.yml
- .github/workflows/integration_test.yml
- spec/spec_helper_acceptance_local.rb
While working on PIE-1181 I found that the endpoint utilizes to retrieve events from Splunk has been marked as deprecated. This PR updates that endpoint.
* Updated endpoint to **v2** in `get_splunk_report()` within the `spec_helper_acceptance_local.rb` file.
> (PIE-1279) Update deprecated Splunk endpoint

- .github/workflows/integration_test.yml
- plans/acceptance/pe_server_setup.pp
- spec/acceptance/events_processor_spec.rb
- spec/spec_helper_acceptance_local.rb
- templates/splunk_hec.yaml.epp
While setting up rspec tests I found that filtering does not work for `pe-console` and `code-manager`. This is a result of the processor script looking for `splunk_hec` settings named `pe-console_data_filter` and `code-manager_data_filter` when the template file for settings has the them named `pe_console_data_filter` and `code_manager_data_filter`.
* Update `templates/splunk_hec.yaml.epp` with correct setting names.
* Add tests for `pe-console` events:
* `spec/acceptance/events_processor_spec.rb`
* `spec/spec_helper_acceptance_local.rb`
* Update `.github/workflows/integration_test.yml` to test on PE LTS.
> (PIE-1289) Event Filtering Bug Fix

- spec/acceptance/class_spec.rb
- spec/spec_helper_acceptance_local.rb
This commit tests against the ability to send Puppet facts to Splunk.
`spec/acceptance/class_spec.rb`
* Added test for Puppet facts.
`spec/spec_helper_acceptance_local.rb`
* Ensure fact configuration is set in the manifest.
> (PIE-1278) Add facts spec test

- CHANGELOG.md
- REFERENCE.md
- manifests/init.pp
- spec/classes/init_spec.rb
This PR ensures that settings added to `puppet.conf` are removed when `splunk_hec::disabled` to set to **true**.
* Update `manifests/init.pp` to ensure settings are removed from `puppet.conf` when disabled is true.
* Added unit tests to `spec/classes/init_spec.rb`
* Generated updates for `REFERENCE.md`.
* Add changes to `CHANGELOG.md`.
[X] Unit Tests
> (PIE-1104) Disable facts and reports

- CHANGELOG.md
- README.md
- REFERENCE.md
- files/hec_secrets.yaml.epp
- lib/puppet/functions/splunk_hec/secure.rb
- lib/puppet/util/splunk_hec.rb
- manifests/init.pp
- manifests/v2_cleanup.pp
- spec/classes/init_spec.rb
- spec/support/unit/reports/splunk_hec_spec_helpers.rb
- templates/settings.yaml.epp
- templates/util_splunk_hec.erb
This PR utilizes the custom function `splunk_hec::secure` to move credential data to a separate file under a new `splunk_hec` subdir.
* Added `manifests/v2_cleanup.pp`
* Added `files/hec_secrets.yaml.epp`
* Renamed `templates/splunk_hec.yaml.epp` -> `templates/settings.yaml.epp`
* Updated `lib/puppet/functions/splunk_hec/secure.rb`
* Function now accepts and returns a hash instead of string
* Updated `manifests/init.pp`
* Create `/etc/puppetlabs/puppet/splunk_hec` directory for config files. 
* Move credentials to `hec_secrets.yaml`
* Remove `splunk_hec.yaml` via `::v2_cleanup` subclass
* Remove `splunk_hec_routes.yaml` via `::v2_cleanup` subclass
* Updated `lib/puppet/util/splunk_hec.rb`
* Utilize credentials from `hec_secrets.yaml`
* Updated `templates/util_splunk_hec.erb`
* Utilize …
> (PIE-1329) Secure sensitive data

- CHANGELOG.md
- lib/puppet/indirector/facts/splunk_hec.rb
This commit resolves a bug in fact collection where the following warning is falsely logged:
```
2023-07-11T19:16:48.368Z WARN  [qtp255490452-712] [puppetserver] Puppet Rescued required facts - Please remove the following facts from splunk_hec::facts_blocklist: []
```
This is a result of `rescued_facts` checking for a nil value as opposed to an empty array.
* Updated `CHANGELOG.md`
* Updated `lib/puppet/indirector/facts/splunk_hec.rb` to check for an empty array.
> (PIE-1364) Rescued facts bug fix

- CHANGELOG.md
- lib/puppet/application/splunk_hec.rb
- lib/puppet/util/splunk_hec.rb
- metadata.json
This commit refactors metrics parsing as we no longer support the legacy metrics collected with older versions of the `puppet_metrics_collector`.
* Updated `CHANGELOG.md`
* Updated `metadata.json` to include puppet_metrics_collector v.8.0.0.
* Updated `lib/puppet/application/splunk_hec.rb`.
* Removed `parse_metrics()` function; parsing is done directly in `main`.
* Moved `parse_legacy_metrics()` function to `lib/puppet/util/splunk_hec.rb`.
* Maint changes to `lib/puppet/util/splunk_hec.rb`.
* Pass `:default` (`nil`) for **file** and **line** in `Puppet.warn_once()` 
> (PIE-1374) Refactor metrics parsing

- .github/workflows/ci.yml
- .github/workflows/latest_testing.yml
- .github/workflows/lts_testing.yml
- .github/workflows/nightly_testing.yml
- CHANGELOG.md
- README.md
- REFERENCE.md
- files/hec_secrets.yaml.epp
- lib/puppet/indirector/facts/splunk_hec.rb
- manifests/init.pp
- spec/classes/init_spec.rb
- templates/settings.yaml.epp
- templates/util_splunk_hec.erb
In preparation for v2 of this module, this commit removes the deprecated `reports` parameter, renames the `collect_facts` parameter, and adds two new parameters for event forwarding credentials.
* `manifests/init.pp`
* Added `token_events` and `url_events` parameters for event forwarding.
* Removed deprecated `reports` parameter.
* Renamed `collect_facts` -> `facts_allowlist`.
* `files/hec_secrets.yaml.epp`
* Added event token to template.
* `templates/settings.yaml.epp`
* Added event url to template. 
* `templates/util_splunk_hec.erb`
* Renamed custom *source_type* for event forwarding.
* `lib/puppet/indirector/facts/splunk_hec.rb` 
* Removed comment regarding `collect_facts` parameter name.
* `spec/classes/init_spec.rb`
* Removed unit test against deprecated `reports` parameter.
* …
> (PIE-1363) Parameter name changes and removals

- CHANGELOG.md
- lib/puppet/application/splunk_hec.rb
This commit fixes a bug that was preventing `system_cpu` metrics collected via `puppet_metrics_collector::system` from being shipped to Splunk.
* `lib/puppet/application/splunk_hec.rb`
* Added logic to allow for Array of sar metrics to be shipped to Splunk.
* Previously the code assumed that the metrics would be in Hash format.
* Updated `CHANGELOG.md`
> (MAINT) Bug Fix - ship sar metrics

- CHANGELOG.md
- lib/puppet/reports/splunk_hec.rb
This commit removes logic for supporting Puppet 4.
* `lib/puppet/reports/splunk_hec.rb`
* Removed `if` statement checking `report_format`.
* Updated `CHANGELOG` 
> (PIE-1325) Bug fix job_id and code_id

- README.md
README updates to correct misconfiguration of `splunk_hec` class.
* Updated `README.md`
* Removed suggestion to set `events_reporting_enabled` to **true** as this will fail until `pe_event_forwarding` is properly configured.
* Updated versions of Puppet that we test against.
> (MAINT) README Updates

- .github/workflows/nightly_testing.yml
- lib/puppet/application/splunk_hec.rb
This commit changes the way that system process metrics collected with `sar` are formatted before being sent to Splunk.
Updated `lib/puppet/application/splunk_hec.rb`
* Refactored the formatting on system metrics to set the name as the key and the value as the value. This allows for better parsing in Splunk.
**Original**:
```
name: %user
value: 0.42
```
**New**:
```
%user: 0.42
```
> (PIE-1643) System Metrics Formatting
